### ISSUE TITLE
error mounting when running 'vagrant up'

### ISSUE THREAD

**Issue by vaughansharman** [Hotshotsteam/ionic2-up#1]
Hi. Thanks for sharing! 

I am having an issue when I run vagrant up, I am getting the below error. I believe that this may be due to the command "getent" not existing on the machine and I am currently looking into a fix. But I thought you may have come across this before and when it is fixed then there will be info for the next person (if there are more)

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:

set -e
mount -t vboxsf -o uid=`id -u docker`,gid=`getent group docker | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u docker`,gid=`id -g docker` vagrant /vagrant

The error output from the command was:

mount: mounting vagrant on /vagrant failed: Protocol error
```

**Comment by dsjgordon** [comment]
@vaughansharman Thanks for the feedback.  I just gave this a go with a fresh clone and wasn't able to reproduce.  Virtualbox 5.0.26, Vagrant 1.8.1, Windows 10.

What host OS are you using?

**Comment by vaughansharman** [comment]
No worries. This is running on a:
mac 10.11.4 
VBox 5.1.2
vagrant 1.8.5

I will have another look at this over the next few days and update if I find a solution, cheers

**Comment by dsjgordon** [comment]
Ah, hasn't been tested on mac yet so I expected issues.  Confirming a resolution would be welcome :)

Most likely the Vagrantfile will require an addition for mac to [use NFS](https://www.vagrantup.com/docs/synced-folders/nfs.html).

Something along the lines of:

``` ruby
sync_type = ((/darwin/ =~ RUBY_PLATFORM) != nil) ? "NFS" : nil
//...
config.vm.synced_folder dev_up_config['host_project_path'], dev_up_config['guest_project_path'], create: true, type: sync_type
//...
config.vm.synced_folder dev_up_config['docker_cache_path'], '/docker-cache', type: sync_type
```

**Comment by vaughansharman** [comment]
That seemed to solve the original issue, but creates a few new nfs issues... I might just look at some other options for now and perhaps you can just put a note in the README to say windows only. Thanks for the help though :)
